#!/usr/bin/env python
import sys

C = {} # compound list

def file_parse(argv):
    f = open(argv, 'r')
    line = (f.readline()).split()
    while line:
	C[(line[1], line[2])] = (line[0], int(line[3]))
	line = (f.readline()).split()

    print C

		



def main():
    file_parse(sys.argv[1])

if __name__ == "__main__":
    main()
